#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# Set magic variables for current file & dir
# __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
# __base="$(basename ${__file} .sh)"
# __root="$(cd "$(dirname "${__dir}")" && pwd)"

# magic variables for links
#__file="$(readlink -f ${BASH_SOURCE[0]})"
#__dir="$(cd "$(dirname "${__file}")" && pwd)"

# arg1="${1:-}"

for link in ~/.tmux.conf ~/.vimrc ~/.vimrc.local ~/.bashrc ~/.bashrc.local ~/.emacs ~/.emacs.d/mine/.emacs.local ~/.gitconfig ~/.gitconfig.local; do
    if [[ -L "$link" ]]; then 
        echo -n "${link}..."
        cp --remove-destination "$(readlink ${link})" ${link}
        echo " Done."
    else
        echo "Not a link: ${link}"
    fi
done
