#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

__dir_dotfiles="$(cd "$(dirname "${__sfile}")" && pwd)"

# -------------------------------------------------------------------------------
# GLOBAL VARS/CONSTANTS
# magic variables for links
__sfile="$(readlink -f ${BASH_SOURCE[0]})"
__sdir="$(cd "$(dirname "${__sfile}")" && pwd)"

source ${__sdir}/source/src_bash_install

# install GIT
    loguj -p -ss -t "---" "Installing Git"
    update_repos
    sudo apt-get install git
    (
        sudo apt-get install libcurl4-gnutls-dev libexpat1-dev gettext libz-dev libssl-dev
        sudo apt-get install asciidoc xsltproc docbook2X xmlto
    ) &


    (
    mkdir -p "${HOME}/apps"
    cd "${HOME}/apps"
    if [[ ! -d "${HOME}/apps/git" ]]; then
        git clone git://git.kernel.org/pub/scm/git/git.git "${HOME}/apps/git"
    else
        cd "${HOME}/apps/git"
        git pull
    fi
    ) &

    echo -e '\n=== Waiting for apt-get...\n'
    wait %1 && echo -e '\n=== apt-get done.\n'
    echo -e '\n=== Waiting for git clone/pull...\n'
    wait %2 && echo -e '\n=== git clone/pull done.\n'

    cd "${HOME}/apps/git"
    make prefix=/usr all doc info
    # ... lasted in vb: 14 min

    ${__sudo} make prefix=/usr install install-doc install-html install-info
    # ... lasted in vb: 12s

    loguj -p -se -t "---" "Installing Git"
    exit 0
