#!/usr/bin/env bash

# TODO: create functions: LOG_ERROR, LOG_INFO
# TODO: fzf - cancel interactive script! provide Y
# TODO: change aptget: use apt-cache to check if it's updated or older version. If older, then update it.
# NEW OPTIONS
#    -u :: update
#    -oc -ol -oh -ow

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# Set magic variables for current file & dir
# __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
# __base="$(basename ${__file} .sh)"
# __root="$(cd "$(dirname "${__dir}")" && pwd)"

# magic variables for links
__file="$(readlink -f ${BASH_SOURCE[0]})"
__dir="$(cd "$(dirname "${__file}")" && pwd)"

# arg1="${1:-}"
# ================================================================================
# UPDATE GLOBAL VARS


__myos="$(uname -s)"
__myhost="$(uname -n)"
            case ${__myos} in
                CYGWIN*)
                    __myos="CYGWIN"
                    if [[ ${__myhost} = AWA* ]]; then
                        __myhost="W"
                    elif [[ ${__myhost} = HEAVEN ]]; then
                        __myhost="H"
                    else
                        __myhost="OTHER"
                    fi
                    ;;
                Linux)
                    __myos="LINUX"
                    if [[ ${__myhost} = LMQ ]]; then
                        __myhost="H"
                    else
                        __myhost="OTHER"
                    fi
                    ;;
                *)
                    __myos="OTHER"
                    __myhost="OTHER"
                    ;;
            esac
__dir_dlocal="$(cd "$(dirname "${__dir}")" && pwd)/dotfiles.local"
__dir_dlocal="$(readlink -f ${__dir_dlocal})"
hash cygpath 2>/dev/null \
    && __win_appdata="$(cygpath -au ${APPDATA:-})" || __win_appdata=""
hash sudo 2>/dev/null \
    && __sudo="sudo" \
    || __sudo=""

# aptget install cmd:
__aptget_install_cmd=""
if hash apt-get 2>/dev/null; then
    __aptget_install_cmd="${__sudo} apt-get install -qyf"
# else
#     echo "===[A] ERROR: no apt-get tool?"
#     __errors+=("[A] ERROR: no apt-get tool?")
#     return 1
fi

__errors=()

if hash curl 2>/dev/null; then
    __geturl_app="curl -fL -o"
elif hash wget 2>/dev/null; then
    __geturl_app="wget -O"
else
    echo "===ERROR: curl/wget app not present"
    __errors+=("ERROR: curl/wget app not present")
fi

# ================================================================================
#Initial cmds:

mkdir -p ~/apps
mkdir -p ~/.emacs.d/mine
# mkdir -p ~/.emacs.d/evil
[[ -d ${__win_appdata} ]] &&
    mkdir -p ${__win_appdata}/.emacs.d/mine
find ${__dir}/bin -type f -not -name 'create_bash.model' -exec chmod +x {} \;
find ${__dir} -maxdepth 1 -type f -not -name 'install' -exec chmod -x {} \;

# --------------------------------------------------------------------------------
# checksum - return 0 if sum is ok
# $1 = file to check the sum
# $2 =
#      -sha1 [SHA1SUM]
# RETURN VALUES
#    1 = wrong SUM!
# <> 1 = other errors
checksum()
{
    local file=""
    local sum_type
    local sum_value
    while [[ $# > 0 ]]; do
        case "$1" in
            -sha1) # sum type
                shift
                sum_value="$1"
                sum_type="sha1"
                shift
                ;;
            *) # file name to check
                if [[ -n "${file}" ]]; then
                    echo "===[SUM] ERROR: Unknown second option? (${file})"
                    __errors+=("[SUM] ERROR: Unknown second option? (${file})")
                    return 3
                fi

                file="$1"
                shift

                if [[ ! -f "${file}" ]]; then
                    echo "===[SUM] ERROR: File does not exist: ${file} (or is not a file)"
                    __errors+=("[SUM] ERROR: File does not exist: ${file} (or is not a file)")
                    return 2
                fi
                ;;
        esac
    done

    # CHECK SUM:
    case "${sum_type}" in
        sha1)
            sha1sum --status -c <(echo "${sum_value}" "${file}") \
                ||
                {
                    echo "===[SUM] ERROR: Wrong checksum for: ${file}"
                    __errors+=("[SUM] ERROR: Wrong checksum for: ${file}")
                    return 1
                } \
                &&
                {
                    echo "===[SUM] CHECKSUM OK: ${file}"
                    return 0
                }
            ;;
        *)
            echo "===[SUM] ERROR: Unknown sum type: ${sum_type}"
            __errors+=("[SUM] ERROR: Unknown sum type: ${sum_type}")
            return 4
            ;;
    esac
}


# --------------------------------------------------------------------------------
# create_link
# $1 = OPTIONAL
#    = -w - then create windows hard link (otherwise it's linux soft link)
#    = -c - then cp instead of creating link
#    = -n - backup old file/dir (otherwise just remove it)
#    = otherwise create linux soft link
#    = can be EMPTY
# $2 = source file
# $3 = destination = link path/link
create_link()
{
    local parse_params="Y"
    local link_type="LINUX"
    local if_backup="Y"
    while [[ ${parse_params} = "Y" ]]; do
        case $1 in
            -w) link_type="WIN HARD"
                shift
                ;;
            -c) link_type="CP"
                shift
                ;;
            -n) if_backup="N"
                shift
                ;;
            *) parse_params="N"
                ;;
        esac
    done

    local src_file="${1:?\$1 not set}"
    local dst_file="${2:?\$2 not set}"

    # check if src exists:
    if [[ ! -e "${src_file}" ]]; then
        echo "===[L] ERROR: Src file ${src_file} does not exists."
        __errors+=("[L] ERROR: Src file ${src_file} does not exists.")
        return 0
    fi
    src_file="$(readlink -f ${src_file})"

    # check if parent directory of dst exists:
    if [[ ! -d "$(cd "$(dirname "${dst_file}")" && pwd)" ]]; then
        echo "[L] Parent directory of ${dst_file} does not exists."
        __errors+=("[L] Parent directory of ${dst_file} does not exists.")
        return 0
    fi

    # dst_file="$(readlink -f ${dst_file})"

    # remove dst if it's a link
    if [[ -L "${dst_file}" ]]; then
        rm "${dst_file}"
    fi

    # echo "${src_file}"
    # echo "${dst_file}"

    # backup dst
    if [[ -f ${dst_file} && ! -L ${dst_file} ]]; then
        if [[ ${if_backup} = "Y" ]]; then
            local backup_file="${dst_file}.old"
            if [[ -e ${backup_file} ]]; then
                echo "===[L] NOT doing backup, it already exists (${backup_file})"
                rm -rf "${dst_file}"
            else
                echo "===[L] Backup ${backup_file}"
                mv "${dst_file}" "${backup_file}"
            fi
        else
            rm -rf "${dst_file}"
        fi
    fi

    # create link
    if [[ $link_type = "WIN HARD" ]]; then
        echo "===[L] LINK Windows ---${dst_file}--- to ---${src_file}---... "
        if [[ -d ${src_file} ]]; then
            cmd /c mklink /J "$(cygpath -aw ${dst_file})" "$(cygpath -aw ${src_file})"
        else
            cmd /c mklink /H "$(cygpath -aw ${dst_file})" "$(cygpath -aw ${src_file})"
        fi
    elif [[ $link_type = "CP" ]]; then
        echo -n "===[L] COPY ${dst_file} ---to--- ${src_file} ---... "
        cp "${src_file}" "${dst_file}"
    elif [[ $link_type = "LINUX" ]]; then
        echo -n "===[L] LINK Linux ${dst_file} ---to--- ${src_file} ---... "
        ln -s "${src_file}" "${dst_file}"
    else
        echo "===[L] ERROR: bledny link_type: ${link_type}"
        __errors+=("[L] ERROR: bledny link_type: ${link_type}")
    fi &&
    {
        echo "===[L] Done."
    } ||
    {
        echo $'\n'"===[L] ERROR! ================================"
        __errors+=("[L] ERROR: creating link ${src_file}")
    }

}

# --------------------------------------------------------------------------------
# aptget
# $1 = app name to install (passed to apt-get)
# $2 = app name to check if it's installed already
aptget()
{
    local app_install="${1:?Error: app name not set}"
    local app_run="${2:-${1}}"

    # check if app is installed
    if hash ${app_run} 2>/dev/null; then
        echo "===[A] ${app_run} already installed."
        return 0
    fi

    # build instal command
    # add sudo
    # instal_cmd="${instal_cmd}sudo "

    # add apt-get
    if [[ -z "${__aptget_install_cmd}" ]]; then
        echo "===[A] ERROR: no apt-get tool (${app_install})"
        __errors+=("[A] ERROR: no apt-get tool (${app_install})")
        return 1
    fi

    local install_cmd="${__aptget_install_cmd} ${app_install}"
    echo "===[A] Installing..."
    ${install_cmd} \
        ||
        {
            echo "===[A] ERROR: installing ${app_install}"
            __errors+=("[A] ERROR: installing ${app_install}")
            return 1

        } \
        &&
        {
            echo "===[A] Done."
        }
}


# --------------------------------------------------------------------------------
# gitclone
# $1  = git url to clone
# $2  = git folder to clone to
# $3- = script to run after cloning
gitclone()
{
    local giturl="${1:?Error: Git url not set}"
    local gitfolder="${2:?Error: Git folder not set}"
    shift
    shift
    local runlater=("$@")

    if [[ -d ${gitfolder} ]]; then
        echo "===[G] folder already exists: ${gitfolder}"
        return 0
    fi
    echo "===[G] git clone ${giturl} ${gitfolder}==="
    git clone "${giturl}" "${gitfolder}" ||
        {
            echo "===[G] Git clone exited with Error: ${giturl} ${gitfolder}"
            __errors+=("[G] Git clone exited with Error: ${giturl} ${gitfolder}")
            return 1
        }

    cd ${gitfolder}
    for run in "${runlater[@]:-}" ; do
        echo "===[G] run ${run}"
        ${run}
    done
}


# --------------------------------------------------------------------------------
# geturl [OPTIONS] <URL> <FILE> [OPTIONS] [RUN_LATER]
# OPTIONS:
#     -u    :: update (delete the file/folder and redownload it)
#     -d    :: delete the file bofore downloading and after succussful install
#     -sha1 <SUM> :: sha1sum of the file to check. If it fails, file is not installed
geturl()
{
    local update=""
    local url=""
    local file=""
    local sum_type=""  # for checksum()
    local sum_value="" # for checksum()
    local if_moved_to_tmpfile=0
    local if_del=0

    while [[ $# > 0 ]]; do
        case "$1" in
            -u)
                shift
                update="Y"
                ;;
            -d)
                shift
                if_del=1
                ;;
            -sha1)
                shift
                sum_value="${1}"
                sum_type="sha1"
                shift
                ;;
            *)
                if [[ -z "${url}" ]]; then
                    url="${1}"
                    shift
                elif [[ -z "${file}" ]]; then
                    file="${1}"
                    shift
                else
                    break
                fi
                ;;
        esac
    done
    if [[ ${if_del} = 1 ]]; then
        rm -rf "${file}"
    fi

    local runlater=("$@")
    tmpfile="${file}#.#"

    if [[ -z "${__geturl_app}" ]]; then
        echo "===[U] ERROR: No curl/wget app: ${url}"
        __errors+=("[U] ERROR: No curl/wget app: ${url}")
        return 99
    fi


    # [[ ! -z "${file}" ]] && file="-o ${file}"

    if [[ "${update}" = "Y" && -e ${file} ]]; then
        mv "${file}" "${tmpfile}"
        if_moved_to_tmpfile=1
    elif [[ -e ${file} ]]; then
        echo "===[U] File/dir already exists: ${file} . Not redownloading."
        return 0
    fi

    # download:
    echo "===[U] Downloading ${url}..."
    ${__geturl_app} ${file} ${url} \
        ||
        {
            echo "===[U] ERROR downloading file: ${url}"
            __errors+=("[U] ERROR downloading file: ${url}")
            if [[ ${if_moved_to_tmpfile} = 1 ]]; then
                echo -n "===[U] Restoring old one... "
                mv -f ${tmpfile} ${file}
                echo "Done."
            fi
            return 1
        }

    # check sum:
    if [[ -n ${sum_type} ]]; then
        checksum ${file} -${sum_type} ${sum_value} ||
            {
                echo "===[U] ERROR checksum: not installing: ${url}"
                __errors+=("[U] ERROR checksum: not installing: ${url}")
                if [[ ${if_moved_to_tmpfile} = 1 ]]; then
                    echo -n "===[U] Restoring old one... "
                    mv -f ${tmpfile} ${file}
                    echo "Done."
                fi
                return 1
            }
    fi

    echo "===[U] Done."
    if [[ ${if_moved_to_tmpfile}=1 && -e ${tmpfile} ]]; then
        rm -rf "${tmpfile}"
    fi

    cd "$(cd "$(dirname "${file}")" && pwd)"
    for run in "${runlater[@]:-}" ; do
        echo "===[U] run ${run}"
        ${run}
    done

    if [[ ${if_del} = 1 ]]; then
        rm -rf "${file}"
    fi

}


# --------------------------------------------------------------------------------
# pipinstall
# $1 = options
#      -2  :: pip2
#      -3  :: pip3
#      -u  :: update
# $1 = app name to install
pipinstall()
{
    local pip="pip"
    local update=""
    local cmdinstall=""
    while [[ $# > 0 ]]; do
        case "$1" in
            -2)
                shift
                pip="pip2"
                ;;
            -3)
                shift
                pip="pip3"
                ;;
            -u)
                shift
                update="-U"
                ;;
            *)
                break;
                ;;
        esac
    done
    cmdinstall="${1}"

    if ${pip} -q show ${cmdinstall}; then # app is installed
        if [[ -z "${update}" ]]; then
            echo "===[P] app already installed: ${cmdinstall}"
            return 0
        fi
    fi
    echo "===[P] installing ${cmdinstall}..."
    ${__sudo} ${pip} install ${update} ${cmdinstall} \
        && echo "===[P] Done." \
        ||
        {
            echo "===[P] ERROR."
            __errors+=("[P] ERROR: ${__sudo} ${pip} install ${update} ${cmdinstall}")
        }
}


# --------------------------------------------------------------------------------
# break_links()
break_links()
{
    echo "===<<< BREAKING LINKS >>>==="
    for link in ~/.tmux.conf ~/.vimrc ~/.vimrc.local ~/.bashrc ~/.bashrc.local ~/.emacs ~/.emacs.d/mine/.emacs.local ~/.gitconfig ~/.gitconfig.local ~/.config/ranger/rc.conf ~/.config/ranger/rifle.conf ~/.mplayer/config ~/.mplayer/input.conf; do
        if [[ ! -e "$link" ]]; then
            echo "File does not exist: $link"
        elif [[ -L "$link" ]]; then
            echo -n "${link}..."
            cp --remove-destination "$(readlink ${link})" ${link}
            echo " Done."
        else
            echo "Not a link: ${link}"
        fi
    done
    echo "===<<< DONE BREAKING LINKS >>>==="
}


# --------------------------------------------------------------------------------
# --------------------------------------------------------------------------------
# --------------------------------------------------------------------------------
# install_dotfiles
install_dotfiles()
{
    echo "===<<< INSTALLING DOTFILES >>>==="

    # Folders:
    create_link ${__dir} ~/.dotfiles
    [[ -d ${__dir_dlocal} ]] && create_link ${__dir_dlocal} ~/.dotfiles.local
    [[ -d ${__dir_dlocal} ]] && chmod -x ${__dir_dlocal}/*

    # TMUX
    create_link ${__dir}/tmux.conf ~/.tmux.conf

    # Git
    create_link ${__dir}/gitconfig ~/.gitconfig
    [[ -d ${__dir_dlocal} ]] && create_link ${__dir_dlocal}/gitconfig.local ~/.gitconfig.local

    # Bash:
    create_link ${__dir}/bashrc ~/.bashrc
    [[ -d ${__dir_dlocal} ]] && create_link ${__dir_dlocal}/bashrc.local ~/.bashrc.local


    # Vim
    create_link ${__dir}/vimrc ~/.vimrc
    [[ -d ${__dir_dlocal} ]] && create_link ${__dir_dlocal}/vimrc.local ~/.vimrc.local

    # Emacs Linux:
    if hash emacs 2>/dev/null; then
        create_link ${__dir}/emacs ~/.emacs
        [[ -d ${__dir_dlocal} ]] && create_link ${__dir_dlocal}/emacs.local ~/.emacs.d/mine/.emacs.local
    fi

    # Emacs Win:
    if [[ -d ${__win_appdata} ]]; then
        create_link -w -n ${__dir}/emacs ${__win_appdata}/.emacs
        [[ -d ${__dir_dlocal} ]] && create_link -w -n ${__dir_dlocal}/emacs.local ${__win_appdata}/.emacs.d/mine/.emacs.local
        # evil-leader:
        create_link -w -n ~/.emacs.d/mine/evil-leader.el ${__win_appdata}/.emacs.d/mine/evil-leader.el
        # key-chord:
        create_link -w -n ~/.emacs.d/mine/key-chord.el ${__win_appdata}/.emacs.d/mine/key-chord.el
        # evil:
        create_link -w -n ~/.emacs.d/evil ${__win_appdata}/.emacs.d/evil
        # org-mode:
        create_link -w -n ~/.emacs.d/org-mode ${__win_appdata}/.emacs.d/org-mode
    fi

    # Emacs local files Linux + Win
    if [[ -d ${__dir_dlocal} ]]; then
        create_link ${__dir_dlocal} ~/.dotfiles.local
        create_link ${__dir_dlocal}/bashrc.local ~/.bashrc.local
        create_link ${__dir_dlocal}/vimrc.local ~/.vimrc.local
        create_link ${__dir_dlocal}/gitconfig.local ~/.gitconfig.local
        create_link ${__dir_dlocal}/emacs.local ~/.emacs.d/mine/.emacs.local
        [[ -d ${__win_appdata} ]] && create_link -w -n ${__dir_dlocal}/emacs.local ${__win_appdata}/.emacs.d/mine/.emacs.local
    else
        echo "===Error: local dir does not exist=${__dir_dlocal}"
        __errors+=("ERROR: local dir does not exist=${__dir_dlocal}")
    fi

    #Ranger:
    # if hash ranger 2>/dev/null; then
    #     sed -i 's/^set column_ratios 1,5,3$/set column_ratios 1,3,4' ~/.config/ranger/rc.conf
    # fi
    if hash ranger 2>/dev/null; then
        find ~/.config/ranger -type f -not -name 'bookmarks' -not -name 'history' -not -name 'tagged' -exec rm -rf {} \;
        ranger --copy-config=all
        sed -i 's/^set column_ratios 1,3,4$/set column_ratios 1,5,3/;
        s/^set show_hidden false$/set show_hidden true/;
        s/^set preview_files true$/set preview_files false/
        s/^set preview_files true$/set preview_files false/
        s/^set preview_directories true$/set preview_directories false/' ~/.config/ranger/rc.conf


        if [[ -d "${__dir_dlocal}" ]]; then
            case ${__myos} in
                CYGWIN)
                    if [[ ${__myhost} = W ]]; then
                        # create_link ~/.dotfiles.local/rifle.conf.w.cygwin ~/.config/ranger/rifle.conf
                        cat ~/.config/ranger/rifle.conf ${__dir_dlocal}/rifle.conf.w.cygwin > ~/.config/ranger/rifletmp.conf
                        mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
                    elif [[ ${__myhost} = H ]]; then
                        # create_link ~/.dotfiles.local/rifle.conf.h.cygwin ~/.config/ranger/rifle.conf
                        cat ~/.config/ranger/rifle.conf ${__dir_dlocal}/rifle.conf.h.cygwin > ~/.config/ranger/rifletmp.conf
                        mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
                    else
                        echo "Cygwin-other os: copying default rifle.conf"
                        __errors+=("Unknown os: copying default rifle.conf")
                        cat ~/.config/ranger/rifle.conf ${__dir}/rifle.conf > ~/.config/ranger/rifletmp.conf
                        mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
                    fi
                    ;;
                LINUX)
                    if [[ ${__myhost} = H ]]; then
                        # create_link ~/.dotfiles.local/rifle.conf.h.linux ~/.config/ranger/rifle.conf
                        cat ~/.config/ranger/rifle.conf ${__dir_dlocal}/rifle.conf.h.linux > ~/.config/ranger/rifletmp.conf
                        mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
                    else
                        echo "Linux-other os: copying default rifle.conf"
                        __errors+=("Unknown os: copying default rifle.conf")
                        cat ~/.config/ranger/rifle.conf ${__dir}/rifle.conf > ~/.config/ranger/rifletmp.conf
                        mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
                    fi
                    ;;
                *)
                    echo "Other os: copying default rifle.conf"
                    __errors+=("Unknown os: copying default rifle.conf")
                    cat ~/.config/ranger/rifle.conf ${__dir}/rifle.conf > ~/.config/ranger/rifletmp.conf
                    mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
                    ;;
            esac
        else
            echo "No local dotfiles, copying default rifle.conf"
            __errors+=("No local dotfiles: copying default rifle.conf")
            cat ~/.config/ranger/rifle.conf ${__dir}/rifle.conf > ~/.config/ranger/rifletmp.conf
            mv ~/.config/ranger/rifletmp.conf ~/.config/ranger/rifle.conf
        fi
    else
        echo "===Ranger folder not found. Not creating links."
        __errors+=("Ranger folder not found. Not creating links.")
    fi

    # mplayer
    if hash mplayer 2>/dev/null || [[ -d ~/.mplayer ]]; then
        create_link ${__dir}/mplayer_config ~/.mplayer/config
        create_link ${__dir}/mplayer_input.conf ~/.mplayer/input.conf
    fi

    vim +PluginInstall +PluginClean +qall

    echo "===<<< DONE INSTALLING DOTFILES >>>==="

}

# -------------------------------------------------------
# install_more_apps
install_more_apps()
{

    echo "===<<< INSTALLING MORE APPS >>>==="

    # update repositories
    # if hash apt-get 2>/dev/null; then
    #     ${__sudo} apt-get update
    # fi

    # Emacs
    aptget emacs || true
    if hash emacs 2>/dev/null; then
        # evil-leader:
        geturl https://raw.githubusercontent.com/cofi/evil-leader/master/evil-leader.el ~/.emacs.d/mine/evil-leader.el -sha1 00c336e55307dbcb3f73f47b1d9a1d759404341d || true
        # key-chord:
        geturl http://www.emacswiki.org/emacs/download/key-chord.el ~/.emacs.d/mine/key-chord.el -sha1 2da61bf970ca332c4de96c1977fc7e326df6c33a || true
        # evil:
        gitclone https://gitorious.org/evil/evil.git ~/.emacs.d/evil \
            ||
            {
                echo "=== Manually downloading evil.git"
                rm -rf ~/.emacs.d/evil
                rm -rf ~/.emacs.d/lyro-evil*
                cd ~/.emacs.d
                if [[ ! -f evil-default.zip ]]; then
                    ${__geturl_app} evil-default.zip https://bitbucket.org/lyro/evil/get/default.zip \
                        ||
                        {
                            echo "=== ERROR: downloading evil.git (default.zip)"
                            __errors+=("ERROR: downloading evil.git (default.zip)")
                        } \
                        &&
                        {
                            unzip evil-default.zip
                            mv ~/.emacs.d/lyro-evil* evil
                            rm ~/.emacs.d/evil-default.zip
                            echo "=== evil.git installed"
                            __errors+=("OK: evil.git installed manually!")
                        }
                fi
            }
        # org-mode:
        gitclone git://orgmode.org/org-mode.git ~/.emacs.d/org-mode "git checkout -b stable origin/maint" "git pull" "make autoloads" || true
    fi

    # commacd
    geturl https://raw.githubusercontent.com/shyiko/commacd/master/commacd.bash ~/.commacd.bash || true
    # geeknote
    gitclone https://github.com/VitaliyRodnenko/geeknote.git ~/apps/geeknote "${__sudo} python setup.py install" "geeknote settings --editor vim" || true

    # glances
    aptget glances \
        &&
        {
            aptget lm-sensors || true
            pipinstall -2 PySensors
        } || true

    # Reszta 2:
    pipinstall -3 BeautifulSoup4
    pipinstall -3 flake8
    pipinstall -3 bashate
    pipinstall -2 speedtest-cli
    pipinstall httpie

    # fzf - asks questions
    if [[ ! -d ~/.fzf ]]; then
        git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf && ~/.fzf/install
    fi

    # geeknote login
    echo "===<<< DONE INSTALLING MORE APPS >>>==="

}

# -------------------------------------------------------
# install_basics
install_basics()
{

    echo "===<<< INSTALLING BASICS >>>==="

    # update repositories
    # if hash apt-get 2>/dev/null; then
    #     ${__sudo} apt-get update
    # fi

    # Basic
    aptget git || true
    aptget vim || true
    aptget make || true
    gitclone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim || true
    if hash python2 2>/dev/null; then
        aptget python-pip pip \
            ||
            {
                geturl https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py -sha1 89eb61fc5b59f14df7f0aa7b020afb5a6ded2e14 "sudo python2 get-pip.py" "rm get-pip.py"
            }
    fi

    if hash python3 2>/dev/null; then
        aptget python3-pip pip3 \
            ||
            {
                geturl https://bootstrap.pypa.io/get-pip.py /tmp/get-pip.py -sha1 89eb61fc5b59f14df7f0aa7b020afb5a6ded2e14 "sudo python3 get-pip.py" "rm get-pip.py"
            }
    fi

    # Ranger
    # rm -rf ~/apps/ranger ~/.config/ranger
    gitclone https://github.com/hut/ranger.git ~/apps/ranger "${__sudo} make install" "ranger --copy-config=all" || true

    # TMUX
    aptget tmux || true

    # Reszta 1:
    aptget wget && __geturl_app="wget -O" || true
    aptget curl && __geturl_app="curl -o" || true
    aptget dtrx ||
        {
            rm -rf /tmp/dtrx-7.1
            geturl -d http://brettcsmith.org/2007/dtrx/dtrx-7.1.tar.gz /tmp/dtrx-7.1.tar.gz -sha1 05cfe705a04a8b84571b0a5647cd2648720791a4 "tar -xf dtrx-7.1.tar.gz" "cd dtrx-7.1" "${__sudo} python setup.py install --prefix=/usr/local" "rm -rf /tmp/dtrx-7.1" "rm -rf /tmp/dtrx-7.1.tar.gz"
        }

    # fasd
    gitclone https://github.com/clvv/fasd.git ~/apps/fasd "${__sudo} make install" || true

    echo "===<<< DONE INSTALLING BASICS >>>==="
}

# -------------------------------------------------------
# -------------------------------------------------------
# -------------------------------------------------------


if_dotfiles="N"
if_basics="N"
if_more_apps="N"
if_break_links="N"

[[ $# = 0 ]] && if_dotfiles="Y"

while [[ $# > 0 ]]; do
    case "$1" in

        -h|--help)
            echo "CLI options:"
            echo "  -d  :: install dotfiles"
            echo "  -b  :: install basic apps"
            echo "  -a  :: install almost all (except more apps)"
            echo "  -A  :: install all/everything"
            echo "  -l :: break links"
            exit 0
            ;;

        -d)
            shift
            if_dotfiles="Y"
            ;;

        -b)
            shift
            if_break_links="Y"
            if_basics="Y"
            ;;

        -l)
            shift
            if_break_links="Y"
            ;;

        -a) # almost all (without more apps)
            shift
            if_break_links="Y"
            if_basics="Y"
            if_dotfiles="Y"
            ;;

        -A) # all (with more apps)
            shift
            if_break_links="Y"
            if_basics="Y"
            if_more_apps="Y"
            if_dotfiles="Y"
            ;;

        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# # start
# geturl https://raw.githubusercontent.com/cofi/evil-leader/master/evil-leader.el ~/.emacs.d/mine/evil-leader.el -sha1 00c336e55307dbcb3f73f47b1d9a1d759404341d || true
# exit
# # end

[[ ${if_break_links} = "Y" ]] && break_links

# update repos?
if [[ ( ${if_basics} = "Y" || ${if_more_apps} = "Y" ) ]] && hash apt-get 2>/dev/null; then
    read -p "Do apt-get update (y/n)? " -n 1 -r
    echo
    if [[ ${REPLY} =~ ^[Yy]$ ]]; then
        ${__sudo} apt-get update
    fi

fi

[[ ${if_basics} = "Y" ]] && install_basics
[[ ${if_more_apps} = "Y" ]] && install_more_apps
[[ ${if_dotfiles} = "Y" ]] && install_dotfiles

# display errors
if [[ ${#__errors[@]} > 0 ]]; then
    echo "=== ERRORS ==="
    for err in "${__errors[@]}"; do
        echo ${err}
    done
else
    echo "Done. No Errors"
fi

