#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset
# set -o xtrace

# Set magic variables for current file & dir
# __dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# __file="${__dir}/$(basename "${BASH_SOURCE[0]}")"
# __base="$(basename ${__file} .sh)"
# __root="$(cd "$(dirname "${__dir}")" && pwd)"

# magic variables for links
#__file="$(readlink -f ${BASH_SOURCE[0]})"
#__dir="$(cd "$(dirname "${__file}")" && pwd)"

# arg1="${1:-}"

create_link()
{
    src_file="${1:?\$1 not set}"
    dst_file="${2:?\$2 not set}"
    src_file="$(readlink -f ${src_file})"
    # dst_file="$(readlink -f ${dst_file})"

    # check if src exists:
    if [[ ! -f "${src_file}" ]]; then
        echo "Error. File ${src_file} does not exists."
        return 1
    fi
    # remove dst if it's a link
    if [[ -L "${dst_file}" ]]; then
        rm "${dst_file}"
    fi

    # echo "${src_file}"
    # echo "${dst_file}"

    # backup dst
    if [[ -f ${dst_file} && ! -L ${dst_file} ]]; then
        mv "${dst_file}" "${dst_file}.old"
    fi
    echo -n "Creating link ---${dst_file}--- to ---${src_file}---... "
    ln -s "${src_file}" "${dst_file}"
    echo "Done."
}

# -------------------------------------------------------


_myos="$(uname)"
_myhost="$(uname -n)"

case ${_myos} in
    CYGWIN*)
        if [[ ${_myhost} = AWA* ]]; then
            create_link ~/.dotfiles.local/rifle.conf.work.cygwin ~/.config/ranger/rifle.conf
        elif [[ ${_myhost} = HEAVEN ]]; then
            create_link ~/.dotfiles.local/rifle.conf.home.cygwin ~/.config/ranger/rifle.conf
        fi
        ;;
    Linux)
        if [[ ${_myhost} = HEAVEN ]]; then
            create_link ~/.dotfiles.local/rifle.conf.home.linux ~/.config/ranger/rifle.conf
        fi
        ;;
    *)
        echo "Error: Unknown host."
        ;;
esac

