#!/usr/bin/env bash

# rap
tmux new-window -n 'rap' -c '/cygdrive/d/Kossak/tasks'
tmux send-keys -t 0 'ranger-cd' Enter

# dotfiles
tmux new-window -n 'dotfiles' -c '~/.dotfiles'
tmux send-keys -t 0 'ranger' Enter
tmux split-window -h -p 50 -c '~/.dotfiles'
tmux send-keys -t 1 'git status' Enter
tmux send-keys -t 1 'git remote show origin' Enter
tmux send-keys -t 1 'git branch -avv' Enter
tmux send-keys -t 1 'git pull'

# english
tmux new-window -n 'english' -c '/cygdrive/d/download/en'
tmux send-keys -t 0 'gn edit 2'
tmux split-window -h -p 50 -c '/cygdrive/d/download/en'
tmux send-keys -t 1 'gn show 2 | tee eng_$(date +"%y%m%d_%H%M%S") | checkeng' Enter

# tmp
tmux new-window -n 'tmp' -c '/cygdrive/d/download'
tmux send-keys -t 0 'ranger-cd' Enter

# backup
tmux new-window -n 'backup' -c '/cygdrive/k/backup_rsync'
tmux send-keys -t 0 'll'

# last
tmux select-window -t 'dotfiles'

