#!/usr/bin/env bash

__myos="$(uname -s)"
__myhost="$(uname -n)"
            case ${__myos} in
                CYGWIN*)
                    __myos="CYGWIN"
                    if [[ ${__myhost} = AWA* ]]; then
                        __myhost="W"
                    elif [[ ${__myhost} = HEAVEN ]]; then
                        __myhost="H"
                    else
                        __myhost="OTHER"
                    fi
                    ;;
                Linux)
                    __myos="LINUX"
                    if [[ ${__myhost} = AWA* || ${__myhost} = lwman || ${__myhost} = wman2 ]]; then
                        __myhost="W"
                    elif [[ ${__myhost} = lman* ]]; then
                        __myhost="H"
                    else
                        __myhost="OTHER"
                    fi
                    ;;
                *)
                    __myos="OTHER"
                    __myhost="OTHER"
                    ;;
            esac

# __myosdist
if [[ -r "/etc/lsb-release" ]] && grep -q 'DISTRIB_ID=LinuxMint' /etc/lsb-release; then
     __myosdist="MINT"
elif [[ -r "/etc/os-release" ]] && grep -q 'NAME="Debian GNU/Linux"' /etc/os-release; then
    __myosdist="DEBIAN"
else
    __myosdist="OTHER"
fi
