#!/usr/bin/env bash

source "${__dir_dotfiles}/source/src_bash_vars_myos"
source "${__dir_dotfiles}/source/src_bash_vars_colors"

# MANUAL SET
# gvim folder

# --------------------------------------------------------------------------------
__my_user=$(echo -n "${USER}")
__logi_errors=()
__logi_info=()
__aptget_check_cmd=""
__aptget_install_cmd=""
__aptget_update_cmd=""

ltype="---"
[[ $# = 0 ]] && __if_dotfiles="Y" || __if_dotfiles="N"
__app_lvl=0
__if_break_links="N"
__if_testing="N"
__if_update="N"
__if_first_time="N"
__if_python_conda="N"
if hash conda 2>/dev/null; then
    __if_python_conda="Y"
fi

if [[ "${__myos}" == "LINUX" ]] && hash sudo 2>/dev/null; then
    __sudo="sudo"
else
    __sudo=""
fi

# --- Windows vars ---------------------------------------------------------------
if hash cygpath 2>/dev/null; then
    __dir_win_home="$(cygpath -au ${APPDATA:-})"
    __dir_win_profile="$(cygpath -au ${USERPROFILE:-})"
else
    __dir_win_home=""
    __dir_win_profile=""
fi
__dir_gvim_root="/cygdrive/d/Kossak/progs/gvim"
if [[ -d "${__dir_gvim_root}" ]]; then
    __dir_gvimplug_path="${__dir_gvim_root}/autoload/plug.vim"
    __dir_gvim_home="/cygdrive/k"
else
    __dir_gvim_root=""
fi

# --------------------------------------------------------------------------------
# __geturl_app
if hash curl 2>/dev/null; then
    __geturl_app="curl -fLo <<FILE>> <<URL>>"
elif hash wget 2>/dev/null; then
    __geturl_app="wget -O <<FILE>> <<URL>>"
elif hash lynx 2>/dev/null; then
    __geturl_app="lynx -dump <<URL>> > <<FILE>>"
else
    loguj -e -t "---" "curl/wget/lynx not present"
fi

# --------------------------------------------------------------------------------
# APT-GET variables
if hash apt-get 2>/dev/null; then
    __aptget_install_cmd="${__sudo} apt-get install -qyf <<APP>>"
    __aptget_update_cmd="${__sudo} apt-get install --only-upgrade <<APP>>"
    __aptget_check_cmd='dpkg -s <<APP>> &>/dev/null'
elif hash pact 2>/dev/null; then
    __aptget_install_cmd="pact install <<APP>>"
    __aptget_update_cmd="pact update <<APP>>"
    __aptget_check_cmd="pact show | grep '^<<APP>>$'"
elif [[ ${__myos} == "CYGWIN" ]]; then

    if ! hash apt-cyg 2>/dev/null; then
        install_url "https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg" "/tmp/apt-cyg" "install /tmp/apt-cyg /bin" "rm /tmp/apt-cyg"
    fi
    if hash apt-cyg 2>/dev/null; then
        __aptget_install_cmd="apt-cyg install <<APP>>"
        __aptget_update_cmd=""
        __aptget_check_cmd="apt-cyg list | grep -q '^<<APP>>$'"
    fi
else
    loguj -w -t "---" "No install_apt command"
fi


# --------------------------------------------------------------------------------

