#!/usr/bin/env bash

source "${__dir_dotfiles}/source/src_bash_vars_myos"
source "${__dir_dotfiles}/source/src_bash_vars_colors"

# MANUAL SET
# gvim folder

# --------------------------------------------------------------------------------
__my_user=$(echo -n "${USER}")
__logi_errors=()
__logi_info=()

ltype="---"
[[ $# = 0 ]] && __if_dotfiles="Y" || __if_dotfiles="N"
__if_break_links="N"
__if_testing="N"

if [[ "${__myos}" == "LINUX" ]] && hash sudo 2>/dev/null; then
    __sudo="sudo"
else
    __sudo=""
fi

# --- Windows vars ---------------------------------------------------------------
if hash cygpath 2>/dev/null; then
    __dir_win_home="$(cygpath -au ${APPDATA:-})"
    __dir_win_profile="$(cygpath -au ${USERPROFILE:-})"
else
    __dir_win_home=""
    __dir_win_profile=""
fi
__dir_gvim_root="/cygdrive/d/Kossak/progs/gvim"
if [[ -d "${__dir_gvim_root}" ]]; then
    __dir_gvimplug_path="${__dir_gvim_root}/autoload/plug.vim"
    __dir_gvim_home="/cygdrive/k"
else
    __dir_gvim_root=""
fi

# --------------------------------------------------------------------------------

