#!/usr/bin/env bash

# add $1 to PATH and export
function add_to_path() {
    local p="$1"
    if [[ -d "$p" && ! "$PATH" =~ (^|:)"$p"($|:) ]]; then
        export PATH="$p:$PATH"
    fi
}

# remove $1 from PATH and export
function del_from_path() {
    local p=$1
    local ps=$1
    ps=$(echo $p | sed 's_/_\\/_g')
    # echo "p = $p"
    if [[ "$PATH" =~ (^|:)"$p"($|:) ]]; then
        export PATH=$(echo $PATH | sed -e "s/:$ps:/::/g" -e "s/^$ps://g" -e "s/:$ps$//g")
    fi
}

# Add anaconda to PATH
function add_anaconda() {
    add_to_path "/home/kossak/anaconda3/bin"
}

# Remove anaconda from path
function del_anaconda() {
    del_from_path "/home/kossak/anaconda3/bin"
}
